# Generated by Django 4.1.2 on 2023-04-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagoryname', models.CharField(max_length=400)),
                ('Pets', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('account_name', models.CharField(max_length=20)),
                ('account_number', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=20)),
                ('status', models.CharField(default='not approved', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Productss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=20)),
                ('product_price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('discount_price', models.BigIntegerField()),
                ('weight', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('description', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.catagory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.signup')),
            ],
        ),
    ]
