# Generated by Django 4.1.2 on 2023-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0002_rename_catagory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productss',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
