# Generated by Django 4.1.2 on 2023-04-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0003_alter_productss_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productss',
            name='seller',
        ),
    ]
